### ISSUE TITLE
Processes support simple events but not ordered graphs of multiple compound events

### ISSUE THREAD

**Issue by adam-burns** [interfacerproject/Interfacer-notebook#2]
Currently processes must be created in a jupyter notebook use case by adding a second append added to the final input event - the second append is for the process, and it is added to the last of the input event definitions, so that the event sequence for a process must be in strict sequence:
- all process events input events
- appended at end of last input event in process, eg: `event_seq.append({'ts': ts, 'event_id':cur_pros['id'], 'action' : cur_pros['name'], 'res_name': cur_res['name'], 'res': cur_res['id']})`
- all process event output events

This does not yet take into account that events in a process are a black box ordered graph of events that themselves will have causal/chronological chains or dependencies, eg events will produce outputs consumed by later input event resources within a process chain.
 
For practical ingest of stepwise assembly instructions of OSH projects, process creation should support easily readable stepwise creation of an ordered graph of multiple events, which will also promote process reuse as VF plans & templates.

**Comment by sbocconi** [comment]
I think that VF processes cannot have a graph of events as input, but we have solved this issue by introducing grouping for processes, for which the "top" process group can contain arbitrary complex (but tree-like) process sub-groups.

This facilitates visualisation as it gives a way to define the level of granularity of the displayed trace graph.
